---
- name: "set root ownership and permissions (/etc/passwd)"
  file: path="{{ item }}" owner="root" group="root" mode=0644
  with_items:
    - "/etc/passwd"
  tags:
    - patch
    - step4

- name: "set root ownership and permissions (/etc/shadow)"
  file: path="{{ item }}" owner="root" group="root" mode=0000
  with_items:
    - "/etc/shadow"
  tags:
    - patch
    - step4

- name: "Local password files must be used in conjunction with 'shadow' password files"
  command: /usr/sbin/pwck -q
  changed_when: 0
  register: result_4_1_2
  failed_when: result_4_1_2.rc != 0
  tags:
    - audit
    - step4

- name: "shadow password files must be readable and writeable by 'root' only"
  debug: msg="Security check non-applicable"
  changed_when: 0
  tags:
    - audit
    - step4

- name: "Set System Default Umask"
  lineinfile:
    dest: /etc/login.defs
    regexp: (?i)^#?UMASK
    line: UMASK 027
  tags:
    - patch
    - step4

- block:
  - name: "Set the users umask to not allow world writeable file to be created"
    lineinfile:
      dest: "{{ item }}"
      regexp: '(\S+)umask'
      line: '        umask 027'
      backrefs: no
    tags:
      - patch
      - step4
    with_items:
      - /etc/profile
      - /etc/bashrc

- name: "Systemd startup files and dependency must be writtable by root"
  debug: msg="Security check non-applicable"
  changed_when: 0
  tags:
    - audit
    - step4
- block:
  - name: "Core dump directory MUST be secured by root"
    file: path="/var/lib/systemd/coredump" owner="root" group="root" mode=0700
    tags:
      - patch
      - step4

  - lineinfile:
      dest: /lib/tmpfiles.d/systemd.conf
      regexp: "(?i)^#?d /var/lib/systemd/coredump.*"
      line: 'd /var/lib/systemd/coredump 0700 root root 3d'
    tags:
      - patch
      - step4

- name: "Shadow password files must be readable and writeable by 'root' only"
  file: path="{{ item }}" owner="root" group="root" mode=0755
  with_items:
    - /etc/udev
    - /dev
  tags:
    - audit
    - step4

- name: "Disable local batch schedulers for non-root users"
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/cron.deny
    - /etc/cron.allow
    - /etc/at.allow
    - /etc/at.deny
  tags:
    - fix
    - step4