---
- name: Install packages (Debian)
  apt: pkg='{{item}}'
  loop:
    - ksh
    - dnsutils
    - ethtool
    - iproute
    - lsof
    - procps
    - sysstat
    - tcpdump
  become: true
  when: ansible_os_family == 'Debian'

