---
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Check ansible version
  fail:
      msg: You must use ansible 2.5 or greater
  when: not ansible_version.full is version('2.5', '>=')
  tags:
    - always

- name: Fail if OS not supported
  fail:
    msg: "This OS is not supported by this role"
  when:
    - ansible_os_family != 'RedHat'
    - ansible_os_family != 'Debian'
  tags:
    - always

- include_tasks: packages.yml

- include_tasks: sysctl.yml

- include_tasks: services.yml

#- include_tasks: minimise-access.yml

- include_tasks: motd.yml

- name: common
  include: hardening/common.yml
  tags:
    - common

#- name: Run Step 1 Fixes
#  include: hardening/step1.yml
#  tags:
#    - step1
#    - fix

- name: Run Step 2 Fixes
  include: hardening/step2.yml
  tags:
    - step2
    - fix

- name: Run Step 3 Fixes
  include: hardening/step3.yml
  tags:
    - fix
    - step3

- name: Run Step 4 Fixes
  include: hardening/step4.yml
  tags:
    - step4
    - fix

- name: Run Step 5 Fixes
  include: hardening/step5.yml
  tags:
    - step5
    - fix

- name: Run Step 6 Fixes
  include: hardening/step6.yml
  tags:
    - step6
    - fix

- name: CIS Section 1 Fixes
  include: hardening/cis-section1.yml
  tags:
    - cis-section1
    - fix

- name: CIS Section 3 Fixes
  include: hardening/cis-section3.yml
  tags:
    - cis-section3
    - fix

- name: CIS Section 4 Fixes
  include: hardening/cis-section4.yml
  tags:
    - cis-section4
    - fix

- name: CIS Section 5 Fixes
  include: hardening/cis-section5.yml
  tags:
    - cis-section5
    - fix

#- name: CIS Section 6 Fixes
#  include: hardening/cis-section6.yml
#  tags:
#    - cis-section6
#    - fix

- include_tasks: gcp-redhat.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_product_name == "Google Compute Engine"