---
- name: Minimise access to important direcories and files
  become: true
  file:
    state: directory
    path: '{{item}}'
    mode: 'go-w'
    recurse: yes
  loop:
    - '/usr'
    - '/usr/sbin'
