---
- name: Install packages
  package:
    name: '{{item}}'
  become: true
  loop: "{{ good_packages }}"

- name: Remove packages
  package:
    name: '{{item}}'
    state: absent
  become: true
  loop: "{{ bad_packages }}"

