---
- name: Include sysctl variables
  include_vars: sysctl.yml

- name: Protect sysctl.conf
  file: path='/etc/sysctl.conf' owner=root group=root mode=0440
  become: true

- name: Set the default mask for all process
  template: src='rhel_sysconfig_init.j2' dest='/etc/sysconfig/init' owner=root group=root mode=0544
  become: true
  when: ansible_os_family == 'RedHat'

- name: Change various sysctl-settings
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{sysctl_config}}'
  become: true
