---
# 1 Initial Setup
- name: "CIS 1.1.1.1 Ensure mounting of cramfs filesystems is disabled"
  copy:
      content: install cramfs /bin/true
      dest: /etc/modprobe.d/disable-cramfs.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "CIS 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled"
  copy:
      content: install freevxfs /bin/true
      dest: /etc/modprobe.d/disable-freevxfs.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "CIS 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled"
  copy:
      content: install jffs2 /bin/true
      dest: /etc/modprobe.d/disable-jffs2.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "CIS 1.1.1.4 Ensure mounting of hfs filesystems is disabled"
  copy:
      content: install hfs /bin/true
      dest: /etc/modprobe.d/disable-hfs.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "CIS 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled"
  copy:
      content: install hfsplus /bin/true
      dest: /etc/modprobe.d/disable-hfsplus.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "1.1.1.6 Ensure mounting of squashfs filesystems is disabled"
  copy:
      content: install squashfs /bin/true
      dest: /etc/modprobe.d/disable-squashfs.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "CIS 1.1.1.7 Ensure mounting of udf filesystems is disabled"
  copy:
      content: install udf /bin/true
      dest: /etc/modprobe.d/disable-udf.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - scored
      - cis-section1

- name: "CIS 1.1.6 Ensure separate partition exists for /var"
  mount:
    name: /tmp
    src: /var/tmp
    fstype: none
    opts: bind
    state: present

- name: "CIS 1.1.15 - 1.1.17 Add nodev, nosuid, noexec to /dev/shm"
  mount:
    name: /dev/shm
    src: tmpfs 
    fstype: tmpfs
    opts: rw,nosuid,nodev,seclabel,noexec
    state: present

- name: "CIS 1.2.5 Disable the rhnsd Daemon (rhnsd)"
  shell: "yum --quiet list installed rhnsd 2>/dev/null"
  register: result_cis_1_2_4
  changed_when: result_cis_1_2_4.stdout
  failed_when: 0
  tags:
   - level1
   - not-scored
   - cis-section1
  when: ansible_distribution == 'RedHat'

- name: "CIS 1.2.5 Disable the rhnsd Daemon (rhnsd)"
  service:
    name: rhnsd
    enabled: no
    state: stopped
  tags:
   - level1
   - not-scored
   - cis-section1
  when:
    - ansible_distribution == 'RedHat'
    - result_cis_1_2_4.rc == 0

- name: "CIS 1.4.1 Check bootloader config are configured"
  stat:
    path: /boot/grub2
  register: result_cis_1_4_1_stat

- name: "CIS 1.4.1 Ensure permissions on bootloader config are configured"
  file:
    state: touch
    dest: "/boot/grub2/grub.cfg"
    owner: "root"
    group: "root"
    mode: "0600"
  when: result_cis_1_4_1_stat.stat.exists
  tags:
    - level1
    - scored
    - cis-section1

- name: "CIS 1.4.2 Ensure bootloader password is set"
  copy:
    content: | 
      GRUB2_PASSWORD=grub.pbkdf2.sha512.10000.XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    dest: /boot/grub2/user.cfg
    owner: root
    group: root
    mode: "0600"
  when: result_cis_1_4_1_stat.stat.exists
  tags:
    - level1
    - scored
    - cis-section1
  notify: "Run grub2-mkconfig"

- name: "CIS 1.5.1 Ensure core dumps are restricted "
  lineinfile:
    create: yes
    dest: "/etc/security/limits.conf"
    regexp: '^\*\s+hard\s+core'
    line: '*     hard   core    0'
    backrefs: no
  tags:
    - level1
    - scored
    - cis-section1

- name: "CIS 1.5.1 Ensure core dumps are restricted"
  sysctl:
      name: "fs.suid_dumpable"
      value: 0
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
    - level1
    - scored
    - cis-section1

- name: "CIS 1.5.3 Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: "kernel.randomize_va_space"
      value: 2
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
    - level1
    - scored
    - cis-section1
