---
# These tasks may be used in multiple sections, they are always run
# # but should really be used to provide information to downstream
# # tasks so that they can take action.

- name: "Common execution search path"
  shell: |
    /usr/sbin/ldconfig -v 2>/dev/null |
    /usr/bin/awk -F: '/^\// { print $1 }' |
    /usr/bin/awk 'system("test -L " $1) { print $1 }'
  register: common_execution_search_path
  changed_when: 0
  tags:
    - always

- name: "Find suid + guid programs"
  shell: |
      find / -xdev \( -path /tmp  -o -path /var/tmp \) -prune -o \( -perm -4000 -o -perm -2000 \) |
      grep -Ev '^(/var/tmp|/tmp)'
  register: common_suid_guid_programs
  changed_when: 0
  tags:
    - always

- name: "Common get unlocked system accounts"
  shell: |
    for user in $(awk -F: '($3 < {{ system_uid_max|default(1000) }}) {print $1}' /etc/passwd); do
      passwd -S $user | awk '($2 != "LK") { print $1 }';
    done
  register: common_unlocked_system_accounts
  changed_when: "False"
  tags:
    - always
