---
- block:
  - name: "System logs must be writeable only by root"
    file:
      path: "{{ item }}"
      owner: "{{ sec_log_owner }}"
      mode: "{{ sys_log_mode }}"
    with_items:
      - "{{ sys_logs }}"

  - name: "System logs must be writeable only by root (tmpfiles.d)"
    lineinfile:
      dest: /lib/tmpfiles.d/var.conf
      regexp: "(?i)^#?f {{ item }}.*"
      line: "f {{ item }} {{ sys_log_mode }} {{ sec_log_owner }} -"
    with_items:
      - "{{ sys_logs }}"

- block:
  - name: "Security logs containing security events must only be readable by root"
    file:
      path: "{{ item }}"
      owner: "{{ sec_log_owner }}"
      group: "{{ sec_log_group }}"
      mode: "{{ sec_log_mode }}"
    with_items:
      - "{{ sec_logs }}"
  - name: "Security logs containing security events must only be readable by root (tmpfiles.d)"
    lineinfile:
      dest: /lib/tmpfiles.d/var.conf
      regexp: "(?i)^#?f {{ item }}.*"
      line: "f {{ item }} {{ sec_log_mode }} {{ sec_log_owner }} {{ sec_log_group }} -"
    with_items:
      - "{{ sec_logs }}"
  tags:
    - fix
    - step6

  - name: add log rotation from template
    template:
      src: logrotate.conf.j2
      dest: /etc/logrotate.conf
      backup: yes
      owner: root
      group: root
      mode: 0644
  tags:
    - fix
    - step6