---

- name: "User shells MUST NOT have the privileged escalation bit (setuid / setgid) set"
  file:
    state: touch
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - /bin/bash
  tags:
    - audit
    - step2

- name: "Configuration files used to set user-specific shell settings must be writable by root"
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX 
    recurse: yes
  loop:
    - /etc/profile.d
    - /etc/skel
  tags:
    - audit
    - step2

- name: "'setuid' or 'setgid' executables MUST only be modifiable by the file owner or 'root'"
  file:
    state: touch
    path: "{{ item }}"
    owner: root
    mode: "o-w"
  loop: "{{ common_suid_guid_programs.stdout_lines }}"
  tags:
    - fix
    - step2
  when: common_suid_guid_programs

