---
- name: "Drop malformed packets"
  iptables_raw:
    state: present
    name: drop_malformed_packets
    rules: |
      -A INPUT -p tcp -m tcp --tcp-flags ALL NONE  -j DROP
      -A INPUT -p tcp -m tcp --tcp-flags ALL ALL  -j DROP
  tags:
    - fix
    - step5

- name: "Drop ICMP Timestamp packets"
  iptables_raw:
    state: present
    name: drop_icmp_timestamp
    rules: |
      -A INPUT -p ICMP --icmp-type timestamp-request -j DROP
      -A INPUT -p ICMP --icmp-type timestamp-reply -j DROP
  tags:
    - fix
    - step5

- name: "Ensure suspicious packets are logged"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.default.log_martians: 1
  tags:
    - fix
    - step5

- name: "Ensure broadcast ICMP requests are ignored"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.icmp_echo_ignore_broadcasts: 1
  tags:
    - fix
    - step5

- name: "Ensure packet redirect sending is disabled"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.default.send_redirects: 0
  tags:
    - fix
    - step5

- name: "Ensure packet redirect receiving is disabled"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.default.accept_redirects: 0
    net.ipv4.conf.all.secure_redirects: 0
    net.ipv4.conf.default.secure_redirects: 0
  tags:
    - fix
    - step5

- name: "Ensure IP forwarding is disabled"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.ip_forward: 0
  tags:
    - fix
    - step5

- name: "Ensure source routed packets are not accepted"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.conf.all.accept_source_route: 0
    net.ipv4.conf.default.accept_source_route: 0
  tags:
    - fix
    - step5

- name: "Ensure TCP SYN Cookies is enabled"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.tcp_syncookies: 1
  tags:
    - fix
    - step5

- name: "System uses random sequence numbers"
  sysctl:
    sysctl_file: '/etc/sysctl.d/{{ item.key }}.conf'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.tcp_syncookies: 1
  tags:
    - fix
    - step5
